[package]
name = "viragagyastervezo"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.2"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
warp = { version = "0.4", features = ["server"] }
dotenvy = "0.15"
